FROM nginx:1.17.4-alpine
MAINTAINER Open State Foundation <developers@openstate.eu>

WORKDIR /usr/share/nginx/html

# Debug: use the nginx binary which was compiled with '--with-debug'
# CMD ["nginx-debug", "-g", "daemon off;"]
