"""Add budget field to project and subproject

Revision ID: 34fdf23b763c
Revises: f0bb894bc9e1
Create Date: 2021-06-07 12:57:53.994805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fdf23b763c'
down_revision = 'f0bb894bc9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('subproject', sa.Column('budget', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subproject', 'budget')
    op.drop_column('project', 'budget')
    # ### end Alembic commands ###
