"""Add categories

Revision ID: 576c02dcd565
Revises: e40b22010751
Create Date: 2020-08-26 17:14:41.673924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576c02dcd565'
down_revision = 'e40b22010751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subproject_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subproject_id'], ['subproject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'subproject_id', 'name')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.add_column('payment', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_subproject_name', table_name='subproject')
    op.create_index(op.f('ix_subproject_name'), 'subproject', ['name'], unique=False)
    op.create_unique_constraint(None, 'subproject', ['project_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subproject', type_='unique')
    op.drop_index(op.f('ix_subproject_name'), table_name='subproject')
    op.create_index('ix_subproject_name', 'subproject', ['name'], unique=True)
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'category_id')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
