"""Add hidden to user model

Revision ID: 5ae774be80e2
Revises: 7cbba327356e
Create Date: 2021-04-14 17:21:18.832905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae774be80e2'
down_revision = '7cbba327356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hidden')
    # ### end Alembic commands ###
