"""Add route field to payment model ("inbesteding", "aanbesteding" or "subsidie")

Revision ID: 66ed68cfc3f5
Revises: 34fdf23b763c
Create Date: 2021-06-08 12:46:59.284656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ed68cfc3f5'
down_revision = '34fdf23b763c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('route', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'route')
    # ### end Alembic commands ###
