"""Add mediatype to File model

Revision ID: 77142c3ebcb3
Revises: 66ed68cfc3f5
Create Date: 2021-07-08 16:00:03.007017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77142c3ebcb3'
down_revision = '66ed68cfc3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('mediatype', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'mediatype')
    # ### end Alembic commands ###
