"""Allow one image per user

Revision ID: f0bb894bc9e1
Revises: 5ae774be80e2
Create Date: 2021-04-30 13:36:21.826177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bb894bc9e1'
down_revision = '5ae774be80e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image')
    op.add_column('user', sa.Column('image', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'file', ['image'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'image')
    op.create_table('user_image',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name='user_image_file_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_image_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'file_id', name='user_image_pkey')
    )
    # ### end Alembic commands ###
